### PR TITLE
Add QuickLookASE

### PR DESCRIPTION
**Pull request by rsodre**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you get it on Brew Cask?

**Comment by rsodre** [comment]
Sure, I'll find some time to do it soon.

**Comment by lukasoppermann** [comment]
@rsodre any chance to do it yet?

**Comment by rsodre** [comment]
not yet

**Comment by rsodre** [comment]
QuickLookASE is on cask.
Branch updated with cask instructions, and added to install all.

**Pull request merged**
