### PR TITLE
Add note on how to get plugins working in Catalina

### LINKED ISSUE #114: Can not use with macOS 10.15

### PR DESCRIPTION
**Pull request by jeeftor**
Added a note for how to use the plugins in Catalina.

Fixes #114

### CODE REVIEW

**Comment by adriandmitroca** [comment]
This is great!

You have a typo by the way, attr -> xattr

**Comment by sindresorhus** [comment]
The PR needs a proper title.

**Comment by jeeftor** [comment]
@sindresorhus @adriandmitroca Addressed both issues!

**Comment by JanBobolz** [comment]
This really helped me. Please consider merging.

**Pull request merged**
